name: Tum Veri Botunu Çalıştır

on:
  schedule:
    # 1. HER GÜN (Hafta içi + Hafta sonu) Sabah 10:20 (TR) / 07:20 (UTC)
    - cron: '20 7 * * *'
    
    # 2. SADECE HAFTA İÇİ (Pzt-Cuma) 11:00 ile 17:00 arası saat başı
    - cron: '0 8-14 * * 1-5'
    
    # 3. HER GÜN (Hafta içi + Hafta sonu) Akşam Kapanış 18:15 (TR) / 15:15 (UTC)
    - cron: '15 15 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Kütüphaneleri Yükle
        run: |
          pip install -r requirements.txt

      - name: Gizli Anahtarı Dosyaya Dönüştür
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: |
          echo "$FIREBASE_KEY" > serviceAccountKey.json

      # --- BURASI YENİ: CMC API KEY'İ PYTHON'A VERİYORUZ ---
      - name: Botu Çalıştır
        env:
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
        run: python tumveriyi_cek.py
